<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" :style="style" v-bind="{ ...$attrs }" v-on="{ ...$listeners }"><path d="M912 190h-69.9c-9.8 0-19.1 4.5-25.1 12.2L404.7 724.5 207 474c-6.1-7.7-15.3-12.2-25.1-12.2H112c-6.7 0-10.4 7.7-6.3 12.9l273.9 347c12.8 16.2 37.4 16.2 50.3 0l488.4-618.9c4.1-5.1.4-12.8-6.3-12.8z"/></svg>
</template>

<script lang="ts">
// GENERATED BY `qys-components-cli gen:icon`
// WARN: DO NOT MODIFIED MANUALLY
import { CSSProperties } from 'vue/types/jsx';

@Component({
  componentName: 'icon-check',
})
export default class IconCheck extends Vue {
  /**
   * 图标大小，默认16px
   */
  @Prop()
  size!: number | string;

  /**
   * 双色图标的主色
   */
  @Prop()
  primaryColor!: string;

  get style(): Partial<CSSProperties> {
      let size = this.size;
      if (!size) {
          size = 16;
      }

      const fontSize =
          typeof size === 'number' ? `${size}px` : size;

      const defaultStyle = {
          width: fontSize,
          height: fontSize,
          'min-width': fontSize,
          'min-height': fontSize,
          fill: 'currentColor',
          fontSize,
          ...(this.$attrs.style as any),
      };

      return defaultStyle;
  }
}
</script>
